pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import "../theme"
import "../config"

/// ThemeExportService - System-wide palette broadcasting and export hook.
///
/// Follows Separation of Concerns (SoC) and Domain-Driven Design (DDD):
/// Watches Colors and Config, formats unified theme files (colors.toml and
/// current-palette.json) compatible with Omarchy, terminals, and AI agents,
/// and dispatches optional user theme-set hooks asynchronously.
Singleton {
    id: root

    readonly property string configDir: {
        const xdg = (typeof Quickshell !== "undefined" && Quickshell.env)
            ? Quickshell.env("XDG_CONFIG_HOME") : "";
        const home = (typeof Quickshell !== "undefined" && Quickshell.env)
            ? (Quickshell.env("HOME") || "") : "";
        const base = (xdg && xdg.length > 0) ? xdg : (home + "/.config");
        return base + "/astral-plasma";
    }

    readonly property string tomlPath: root.configDir + "/colors.toml"
    readonly property string jsonPath: root.configDir + "/current-palette.json"
    readonly property string envPath: root.configDir + "/agent-theme.env"
    readonly property string hookPath: root.configDir + "/hooks/on-theme-change.sh"

    function toHex(c) {
        if (!c) return "#000000";
        if (typeof c === "string") return c;
        if (typeof c.toString === "function") {
            const str = c.toString();
            if (str.startsWith("#")) return str;
        }
        return "#" + Math.round(c.r * 255).toString(16).padStart(2, '0')
                   + Math.round(c.g * 255).toString(16).padStart(2, '0')
                   + Math.round(c.b * 255).toString(16).padStart(2, '0');
    }

    function formatToml() {
        const mode = (typeof Colors !== "undefined" && !Colors.isDarkMode) ? "light" : "dark";
        const preset = (typeof Config !== "undefined" && Config.themePreset) ? Config.themePreset : "astral-ai";
        const p = toHex((typeof Colors !== "undefined") ? Colors.primary : "#818cf8");
        const onP = toHex((typeof Colors !== "undefined") ? Colors.onPrimary : "#0f111a");
        const s = toHex((typeof Colors !== "undefined") ? Colors.surface : "#0b0d14");
        const sc = toHex((typeof Colors !== "undefined") ? Colors.surfaceContainer : "#111420");
        const sec = toHex((typeof Colors !== "undefined") ? Colors.secondary : "#38bdf8");
        const tert = toHex((typeof Colors !== "undefined") ? Colors.tertiary : "#c084fc");
        const onS = toHex((typeof Colors !== "undefined") ? Colors.textMain : "#eef2ff");
        const out = toHex((typeof Colors !== "undefined") ? Colors.outlineColor : "#6366f1");

        return '# Auto-generated by Astral Plasma Theme Engine\n'
             + 'mode = "' + mode + '"\n'
             + 'name = "' + preset + '"\n\n'
             + '[colors]\n'
             + 'primary = "' + p + '"\n'
             + 'on_primary = "' + onP + '"\n'
             + 'accent = "' + p + '"\n'
             + 'background = "' + s + '"\n'
             + 'foreground = "' + onS + '"\n'
             + 'surface = "' + s + '"\n'
             + 'surface_container = "' + sc + '"\n'
             + 'secondary = "' + sec + '"\n'
             + 'tertiary = "' + tert + '"\n'
             + 'outline = "' + out + '"\n';
    }

    function formatJson() {
        const mode = (typeof Colors !== "undefined" && !Colors.isDarkMode) ? "light" : "dark";
        const preset = (typeof Config !== "undefined" && Config.themePreset) ? Config.themePreset : "astral-ai";
        const payload = {
            "mode": mode,
            "preset": preset,
            "primary": toHex((typeof Colors !== "undefined") ? Colors.primary : "#818cf8"),
            "on_primary": toHex((typeof Colors !== "undefined") ? Colors.onPrimary : "#0f111a"),
            "surface": toHex((typeof Colors !== "undefined") ? Colors.surface : "#0b0d14"),
            "surface_container": toHex((typeof Colors !== "undefined") ? Colors.surfaceContainer : "#111420"),
            "secondary": toHex((typeof Colors !== "undefined") ? Colors.secondary : "#38bdf8"),
            "tertiary": toHex((typeof Colors !== "undefined") ? Colors.tertiary : "#c084fc"),
            "outline": toHex((typeof Colors !== "undefined") ? Colors.outlineColor : "#6366f1"),
            "on_surface": toHex((typeof Colors !== "undefined") ? Colors.textMain : "#eef2ff"),
            "ai_color": toHex((typeof Colors !== "undefined") ? Colors.aiActivityColor : "#818cf8")
        };
        return JSON.stringify(payload, null, 2);
    }

    function formatEnv() {
        const mode = (typeof Colors !== "undefined" && !Colors.isDarkMode) ? "light" : "dark";
        const preset = (typeof Config !== "undefined" && Config.themePreset) ? Config.themePreset : "astral-ai";
        const p = toHex((typeof Colors !== "undefined") ? Colors.primary : "#818cf8");

        return '# AI Agent & Terminal Environment Sync\n'
             + 'COLOR_SCHEME="' + mode + '"\n'
             + 'ASTRAL_THEME="' + preset + '"\n'
             + 'ANTHROPIC_THEME="' + mode + '"\n'
             + 'OPENCODE_THEME="' + mode + '"\n'
             + 'AGY_THEME="' + mode + '"\n'
             + 'ASTRAL_AI_ACCENT="' + p + '"\n'
             + 'ASTRAL_PRIMARY="' + p + '"\n'
             + 'ASTRAL_SURFACE="' + toHex((typeof Colors !== "undefined") ? Colors.surface : "#0b0d14") + '"\n'
             + 'ASTRAL_AI_COLOR="' + toHex((typeof Colors !== "undefined") ? Colors.aiActivityColor : "#818cf8") + '"\n';
    }

    Timer {
        id: debounceTimer
        interval: 100
        repeat: false
        onTriggered: root.exportTheme()
    }

    readonly property bool syncEnabled: (typeof Config !== "undefined") ? Config.aiThemeSyncEnabled : false

    function scheduleExport() {
        if (!root.syncEnabled) return;
        debounceTimer.restart();
    }

    function exportTheme() {
        if (typeof Quickshell === "undefined" || !Quickshell.execDetached) return;

        const tomlData = root.formatToml();
        const jsonData = root.formatJson();
        const envData = root.formatEnv();

        // Write files via shell command safely to user config
        const cmd = "mkdir -p '" + root.configDir + "' && "
                  + "cat << 'EOF' > '" + root.tomlPath + "'\n" + tomlData + "EOF\n"
                  + "cat << 'EOF' > '" + root.jsonPath + "'\n" + jsonData + "EOF\n"
                  + "cat << 'EOF' > '" + root.envPath + "'\n" + envData + "EOF\n"
                  + "if [ -x '" + root.hookPath + "' ]; then '" + root.hookPath + "' '"
                  + ((typeof Config !== "undefined" && Config.themePreset) ? Config.themePreset : "astral-ai") + "' '"
                  + ((typeof Colors !== "undefined" && !Colors.isDarkMode) ? "light" : "dark") + "' & fi";

        Quickshell.execDetached(["sh", "-c", cmd]);
    }

    // Reactively trigger export when theme preset or dark mode changes
    Connections {
        target: (typeof Config !== "undefined") ? Config : null
        function onThemePresetChanged() { root.scheduleExport(); }
        function onIsDarkModeChanged() { root.scheduleExport(); }
        function onDynamicColorsChanged() { root.scheduleExport(); }
    }

    // Wallpaper-driven (dynamic) palettes change Colors without touching Config
    Connections {
        target: (typeof Colors !== "undefined") ? Colors : null
        function onPrimaryChanged() { root.scheduleExport(); }
        function onSurfaceChanged() { root.scheduleExport(); }
    }

    onSyncEnabledChanged: root.scheduleExport()

    Component.onCompleted: {
        root.scheduleExport();
    }
}
