#!/usr/bin/env bash
# Generates a formatted Conventional Commits changelog between two Git revisions.
# Usage: ./scripts/generate_changelog.sh [FROM_REF] [TO_REF]
set -euo pipefail

TO_REF="${2:-HEAD}"

# Determine FROM_REF if not provided
if [ -n "${1:-}" ]; then
    FROM_REF="$1"
else
    # Try finding the latest reachable tag before TO_REF
    FROM_REF=$(git describe --tags --abbrev=0 "${TO_REF}^" 2>/dev/null || true)
    if [ -z "$FROM_REF" ]; then
        # If no previous tag, find root commit
        FROM_REF=$(git rev-list --max-parents=0 HEAD 2>/dev/null | tail -n 1 || true)
    fi
fi

# Determine commit range
if [ -n "$FROM_REF" ] && git rev-parse --verify "$FROM_REF" >/dev/null 2>&1; then
    RANGE="${FROM_REF}..${TO_REF}"
    RANGE_LABEL="Changes since \`${FROM_REF}\`"
else
    RANGE="${TO_REF}"
    RANGE_LABEL="All commits up to \`${TO_REF}\`"
fi

# Buffers for categories
FEAT=""
FIX=""
REFACTOR=""
PERF=""
DOCS=""
OTHER=""

# Read commits in range: hash|author|subject
while IFS='|' read -r HASH AUTHOR SUBJECT; do
    [ -z "$HASH" ] && continue
    LINE="- ${SUBJECT} ([${HASH}](https://github.com/gitawego/astral-plasma/commit/${HASH})) - @${AUTHOR}"

    case "$SUBJECT" in
        feat*|Feat*)
            FEAT="${FEAT}${LINE}"$'\n'
            ;;
        fix*|Fix*)
            FIX="${FIX}${LINE}"$'\n'
            ;;
        refactor*|Refactor*)
            REFACTOR="${REFACTOR}${LINE}"$'\n'
            ;;
        perf*|Perf*)
            PERF="${PERF}${LINE}"$'\n'
            ;;
        docs*|Docs*)
            DOCS="${DOCS}${LINE}"$'\n'
            ;;
        *)
            OTHER="${OTHER}${LINE}"$'\n'
            ;;
    esac
done < <(git log "${RANGE}" --no-merges --format="%h|%an|%s" 2>/dev/null || true)

# Output formatted Markdown
cat <<EOF
## 🌟 Release Summary (${TO_REF})

${RANGE_LABEL}

EOF

if [ -n "$FEAT" ]; then
    echo "### 🚀 Features"
    echo ""
    echo "$FEAT"
fi

if [ -n "$FIX" ]; then
    echo "### 🐛 Bug Fixes"
    echo ""
    echo "$FIX"
fi

if [ -n "$REFACTOR" ]; then
    echo "### ♻️ Architecture & Refactoring"
    echo ""
    echo "$REFACTOR"
fi

if [ -n "$PERF" ]; then
    echo "### ⚡ Performance Improvements"
    echo ""
    echo "$PERF"
fi

if [ -n "$DOCS" ]; then
    echo "### 📝 Documentation"
    echo ""
    echo "$DOCS"
fi

if [ -n "$OTHER" ]; then
    echo "### 🔧 Maintenance & Tooling"
    echo ""
    echo "$OTHER"
fi

cat <<EOF
---
*Automated release generated by [Astral Plasma](https://github.com/gitawego/astral-plasma) release pipeline.*
EOF
